### ISSUE TITLE
How to hide a function definition

### ISSUE THREAD

**Issue by v1d3rm3** [starbelly/rebar3_ex_doc#17] opened 2022-01-31 17:15 UTC
Is it EDoc compliant?
I decorate function with `@hidden`, but it stills appear in ex_doc page.

**Comment by starbelly** [comment] 2022-02-01 01:21
@v1d3rm3 For ex_doc, `@private` will do the trick. `@hidden` is specific to edoc I believe.

**Comment by starbelly** [comment] 2022-02-20 17:47
I'm going to close this as resolved. Feel free to re-open if you feel there's a problem.

**Comment by eproxus** [comment] 2022-06-08 13:45
I have the same problem. Neither `@hidden` nor `@private` works.

E.g:

```erl

-export([hidden/0]).
-export([private/0]).

% @hidden
hidden() -> ok.

% @private
private() -> ok.
```

**Comment by starbelly** [comment] 2022-06-08 18:21
Yeah, seems to not be working now. We'll have to look into ex_doc as to what the issue is. Need to verify it doesn't happen when running ex_doc on its own.

**Comment by starbelly** [comment] 2022-06-09 02:17
@eproxus This seems to be related to OTP 25. I just published rebar3_hex and it everything was exposed, I then switched to OTP 24 and republished : https://hexdocs.pm/rebar3_hex/7.0.2/api-reference.html#modules

This will take some digging.

**Comment by eproxus** [comment] 2022-06-09 16:36
@starbelly Thanks for looking into it! I’ll use that as a workaround for now 👍

**Closed** 2022-06-21 01:54 UTC

**Comment by starbelly** [comment] 2022-06-21 02:04
@eproxus  This was fixed in #30 and 0.2.12 cut and pushed to hex https://hex.pm/packages/rebar3_ex_doc/0.2.12

**Comment by eproxus** [comment] 2022-06-21 12:39
Lovely! 🙏
