### ISSUE TITLE
rebar3_ex_doc plugin fails when .erl file contains function named `record`

### ISSUE THREAD

**Issue by max-au** [starbelly/rebar3_ex_doc#26] opened 2022-05-25 02:57 UTC
Discovered trying to ex_doc erlperf: https://github.com/max-au/erlperf/blob/master/src/erlperf.erl#L137

Although minimal repro could be just 
```
-module(test).
-export([record/1]).

-spec record(module()) -> [[{module(), atom()}]].
record(Mod) -> [[{Mod, ok}]].
```
Output is:
```
rebar3 hex publish docs
===> Verifying dependencies...
<...>
===> Running ex_doc for erlperf
===> warning: internal inconsistency, please submit bug: "module" != "atom"
  src/test.erl:5: test.record/1


19:56:02.717 [error] Task #PID<0.129.0> started from #PID<0.116.0> terminating
** (MatchError) no match of right hand side value: []
    (ex_doc 0.28.3) lib/ex_doc/language/erlang.ex:558: ExDoc.Language.Erlang.pop/0
    (ex_doc 0.28.3) lib/ex_doc/language/erlang.ex:512: anonymous fn/2 in ExDoc.Language.Erlang.replace/3
```

Renaming `record/1` into `record1/1` makes the error go away.

**Comment by starbelly** [comment] 2022-05-25 04:13
The issue is there is an exception in ex_doc that handles walking the ast for specs. Specifically here : https://github.com/elixir-lang/ex_doc/blob/935f2dac019d0bdcb470e68fc8b077e4e27bfe15/lib/ex_doc/language/erlang.ex#L463

A fix that I came up with is to check to see if the accumulator is empty :


```
 name in [:"::", :when, :%{}, :{}, :|, :->, :record] and acc != [] ->
 ```
 
 But I'm not sure if that's appropriate or introduces other problems. Probably should open an issue on ex_doc.

**Comment by starbelly** [comment] 2022-11-19 16:42
Resolved via https://github.com/elixir-lang/ex_doc/pull/1576

**Closed by starbelly** 2022-11-19 16:42 UTC
